package tugasMhs;


import static tugasMhs.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Antonia Tatartianingsih Abur
 * UAS OOP
 */
public class fTugas extends javax.swing.JFrame {
    DefaultTableModel dtm =new DefaultTableModel();

    /**
     * Creates new form fMahasiswa
     * @throws java.sql.SQLException
     */
    public fTugas() throws SQLException {
        initComponents();
        tTugas.setModel(dtm);
        dtm.addColumn("nim");
        dtm.addColumn("nama_mhs");
        dtm.addColumn("judul_tugas");
        dtm.addColumn("status");
        
        lsDtTugas();
        fieldEnable(false);
        tombol(false);
        cBaru.setEnabled(true);
        cTutup.setEnabled(true);
        
            
    }
    
    private void fieldEnable(boolean opsi){
        txnim.setEditable(opsi);
        txNamaMahasiswa.setEditable(opsi);
        txJudulTugas.setEditable(opsi);
        txStatus.setEditable(opsi);
      }
    
    private void tombol(boolean opsi){
        cBaru.setEnabled(opsi);
        cUbah.setEnabled(opsi);
        cHapus.setEnabled(opsi);
        cTutup.setEnabled(opsi);
    }
    private void clearForm(){
        txnim.setText("");
        txNamaMahasiswa.setText("");
        txJudulTugas.setText("");
        txStatus.setText("");
    }
    
    private void lsDtTugas() throws SQLException{
        Connection cnn = koneksi();
        
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("select * from  mhs;");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                Object[] dta = new Object[4];
                dta[0] = rs.getString("nim");
                dta[1] = rs.getString("nama_mhs");
                dta[2] = rs.getString("judul_tugas");
                dta[3] = rs.getString("status");
                
                dtm.addRow(dta);
            
            }
            cnn.close();
            
            
            
        
        }
    
    }
    
    private void storeData() throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO mhs(nim,nama_mhs,judul_tugas,status) VALUES(?,?,?,?);");
            ps.setString(1, txnim.getText());
            ps.setString(2, txNamaMahasiswa.getText());
            ps.setString(3, txJudulTugas.getText());
            ps.setString(4, txStatus.getText());
            ps.executeUpdate();
            cnn.close();
        }
    }
    private void updateData()throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("UPDATE mhs SET nama_mhs=?, judul_tugas=?, status=? WHERE nim=?;");
            
            ps.setString(1, txNamaMahasiswa.getText());
            ps.setString(2, txJudulTugas.getText());
            ps.setString(3, txStatus.getText());
            ps.setString(4, txnim.getText());
            ps.executeUpdate();
            cnn.close();
        }
    }
    private void destroyData()throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("DELETE FROM mhs WHERE nim=?;");
            ps.setString(1, txnim.getText());
            ps.executeUpdate();
            cnn.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txnim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNamaMahasiswa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txJudulTugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTugas = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("STLiti", 0, 24)); // NOI18N
        jLabel1.setText("Data Tugas Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Cormorant Infant Light", 0, 18)); // NOI18N
        jLabel2.setText("NIM");

        txnim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnimActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cormorant Infant Light", 0, 18)); // NOI18N
        jLabel3.setText("Nama Mahasiswa");

        txNamaMahasiswa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cormorant Infant Light", 0, 18)); // NOI18N
        jLabel4.setText("Judul Tugas");

        txJudulTugas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cormorant Infant Light", 0, 18)); // NOI18N
        jLabel5.setText("Status");

        txStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tTugas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        tTugas.setFont(new java.awt.Font("YouYuan", 0, 12)); // NOI18N
        tTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTugas);

        cBaru.setBackground(new java.awt.Color(204, 204, 204));
        cBaru.setText("Tambah");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cUbah.setBackground(new java.awt.Color(255, 204, 204));
        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cHapus.setBackground(new java.awt.Color(255, 204, 255));
        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cTutup.setBackground(new java.awt.Color(204, 255, 255));
        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txNamaMahasiswa)
                            .addComponent(txnim)
                            .addComponent(txJudulTugas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(326, 326, 326))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(cBaru)
                                            .addGap(18, 18, 18)
                                            .addComponent(cUbah)
                                            .addGap(20, 20, 20)
                                            .addComponent(cHapus)
                                            .addGap(18, 18, 18)
                                            .addComponent(cTutup))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txStatus))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 219, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(txJudulTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBaru)
                    .addComponent(cUbah)
                    .addComponent(cHapus)
                    .addComponent(cTutup))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnimActionPerformed

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
        if (cBaru.getText().equals("Baru")){
            cBaru.setText("Simpan");
            cTutup.setText("Batal");
            cUbah.setEnabled(false);
            cHapus.setEnabled(false);
            clearForm();
            fieldEnable(true);
        }else{
            if(!txnim.getText().equals("")){
                try {
                    storeData();
                    lsDtTugas();
                } catch (SQLException ex) {
                    Logger.getLogger(fTugas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }        
            cBaru.setText("Baru");
            cTutup.setText("Tutup");
            clearForm();
            fieldEnable(false);
        }
    }//GEN-LAST:event_cBaruActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        if(cUbah.getText().equals("Ubah")){
            cUbah.setText("Simpan");
            cTutup.setText("Batal");
            
            cBaru.setEnabled(false);
            cHapus.setEnabled(false);
            fieldEnable(true);
            txnim.setEditable(false);
            
        }else{
            
            try {
                updateData();
                lsDtTugas();               
                clearForm();
                fieldEnable(false);
                
                cUbah.setText("Ubah");
                cTutup.setText("Tutup");
                cBaru.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(fTugas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cUbahActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        
        int jwb = JOptionPane.showOptionDialog(this, "yakin mau menghapus data?" +txnim.getText()+"?", "konfirmasi hapus data",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jwb == JOptionPane.YES_OPTION){
        try {
            destroyData();
            lsDtTugas();
            clearForm();
            cUbah.setEnabled(false);
            cHapus.setEnabled(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(fTugas.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
    }//GEN-LAST:event_cHapusActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        
        if(cTutup.getText().equals("Tutup")){
           int opsi = JOptionPane.showOptionDialog(this,
                "Yakin mau menutup form ",
                "Tutup Form",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(opsi == JOptionPane.YES_OPTION){
            System.exit(0); 
        
        }
        }else{
            cTutup.setText("tutup");
            cBaru.setText("baru");
            cUbah.setText("ubah");
            
        } 
    }//GEN-LAST:event_cTutupActionPerformed

    private void tTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTugasMouseClicked
        
        txnim.setText( tTugas.getValueAt( tTugas.getSelectedRow() , 0).toString() );
        txNamaMahasiswa.setText( tTugas.getValueAt( tTugas.getSelectedRow() , 1).toString() );
        txJudulTugas.setText( tTugas.getValueAt( tTugas.getSelectedRow() , 2).toString() );
        txStatus.setText( tTugas.getValueAt(tTugas.getSelectedRow(), 3).toString());
        
        
        cUbah.setEnabled(true);
        cHapus.setEnabled(true);
        
    }//GEN-LAST:event_tTugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fTugas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fTugas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tTugas;
    private javax.swing.JTextField txJudulTugas;
    private javax.swing.JTextField txNamaMahasiswa;
    private javax.swing.JTextField txStatus;
    private javax.swing.JTextField txnim;
    // End of variables declaration//GEN-END:variables
}
